### ISSUE TITLE
Issues after recent upgrade

### ISSUE THREAD

**Issue by halfagascan** [bebo-dot-dev/m3u-epg-editor#64]
Just discovered the update from May, updated ok.
A couple issues, the big one first.
From cli:
python3 ./m3u-epg-editor-py3.py -m="http://XX.XXXXX.com:2082/get.php?username=XXXXXXX&password=XXXXXXX&type=m3u_plus&output=mpegts" -e="http://XX.XXXXX.com:2082/xmltv.php?username=XXXXXXX&password=XXXXXXX" -g="'US-ENTERTAINMENT','PREMIUM MOVIES'"  -t='false' -r=12 -d="/home/jerry/programs/m3u-epg-editor/output/greyridge/" -f="greyridge" -l="true"
2021-07-01T10:15:26.038543 m3u-epg-editor-py3.py process started with Python v3.9.1 (default, Jan 23 2021, 18:00:22) 
[GCC 8.3.0]
2021-07-01T10:15:26.038861 input script arguments: Namespace(json_cfg=None, m3uurl='http://XX.XXXXX.com:2082/get.php?username=XXXXXXX&password=XXXXXXX&type=m3u_plus&output=mpegts', epgurl='http://XX.XXXXX.com:2082/xmltv.php?username=XXXXXXX&password=XXXXXXX', groups="'US-ENTERTAINMENT','PREMIUM MOVIES'", groupmode='keep', discard_channels=None, include_channels=None, id_transforms=[], group_transforms=[], channel_transforms=[], range='12', sortchannels=None, xml_sort_type='none', tvh_start=None, tvh_offset='rue', no_tvg_id=False, no_epg=False, force_epg=False, no_sort=False, http_for_images=False, preserve_case=False, outdirectory='/home/jerry/programs/m3u-epg-editor/output/greyridge/', outfilename='greyridge', log_enabled=True)
2021-07-01T10:15:26.039272 Traceback (most recent call last):
  File "/home/jerry/programs/m3u-epg-editor/./m3u-epg-editor-py3.py", line 998, in <module>
    main()
  File "/home/jerry/programs/m3u-epg-editor/./m3u-epg-editor-py3.py", line 222, in main
    args = validate_args()
  File "/home/jerry/programs/m3u-epg-editor/./m3u-epg-editor-py3.py", line 303, in validate_args
    args.tvh_offset = int(args.tvh_offset)
ValueError: invalid literal for int() with base 10: 'rue'

2021-07-01T10:15:26.039289 process terminated early due to an exception
2021-07-01T10:15:26.039311 process completed

I do have a .json file, but the newer version doesn't seem to abide by my configuration, I have
 "US-ENTERTAINMENT",
 "PREMIUM MOVIES",
 "Low BW USA",
 "USA SD",
 "US-LOCALS",
 "MUSIC CHOICE",
 "DASH RADIO"
As the only channel groups I would like, yet am getting:
channel element for NHL Detroit Red Wings.us
channel element for NHL Colorado Avalanche.us
channel element for NHL New York Islanders.us
channel element for NHL Columbus Blue Jackets.us
channel element for NHL Minnesota Wild.us
channel element for NHL New York Rangers.us
channel element for NHL Toronto Maple Leafs.us
As well as many foreign channels.

In your example cli's for fab and vader, you show an option for -c, in the useage help, I see no option for -c, maybe a missing letter?
Thanks for putting this together, really helps when trimming down.
raven

**Comment by bebo-dot-dev** [comment]
Hi there,

Good spot on the `-c` argument, thanks. This should have been `-ic` (include_channels) and I've now fixed it up in the [README.md](https://github.com/bebo-dot-dev/m3u-epg-editor/blob/master/README.md).

For your 1st reported issue (`args.tvh_offset = int(args.tvh_offset) ValueError: invalid literal for int() with base 10: 'rue'`) this is an input argument issue. At first I thought you had specified a quoted string rather than an integer value for the `-t / tvh_offset` argument because this would cause this same problem however on closer inspection, it looks like it's the `-l="true"` thing you're using that has it confused. If you're using the cli and you want to enable runtime output to the process.log file just include `-l` in your command line (rather than `-l="true"`). If you do that, this one should be solved.

Not sure what's going on with your 2nd reported issue tbh, there's not enough to go on at the moment.

**Comment by halfagascan** [comment]
Ok, cli ran fine with **-l**, completed and pulled what was requested, but included channels I had specified as not wanting
python3 m3u-epg-editor-py3.py -m="http://XX.XXXX.com:2082/get.php?username=XX.XXXX&password=XX.XXXX&type=m3u_plus&output=mpegts" -e="http://XX.XXXX.com:2082/xmltv.php?username=XX.XXXX&password=XX.XXXX" -g="'US-ENTERTAINMENT','PREMIUM MOVIES'" -d="'BABY FIRST','BABY TV','**ADULT SWIM**','ANTENNA TV','BEACH TV','BET Low','BET','**BET HER** Low','BET JAMS Low','BET SOUL Low','BET WEST','BLACK NEWS CHANNEL','BLOOMBERG TV','Bloomberg Television','BOOMERANG','BOUNCE TV','BOUNCE TV Low','BUZZR','CBN NEWS INTERNATIONAL','C-SPAN','C-SPAN 2','C-SPAN 3','CARS TV'", -r=12 -d="/home/jerry/programs/m3u-epg-editor/output/ridge/" -f="ridge" -l

cat ridge.m3u8 | grep ADULT
#EXTINF:-1 tvg-id="adultswim.us" tvg-name="US: ADULT SWIM (8PM-5AM)" tvg-logo="https://github.com/Tapiosinn/tv-logos/raw/master/countries/united-states/adult-swim-us.png" group-title="US-ENTERTAINMENT",US: ADULT SWIM (8PM-5AM)


What else can I provide?
Thanks
raven

**Comment by bebo-dot-dev** [comment]
if your intention is to use the cli and discard this bunch of channels: 

> "'BABY FIRST','BABY TV','ADULT SWIM','ANTENNA TV','BEACH TV','BET Low','BET','BET HER Low','BET JAMS Low','BET SOUL Low','BET WEST','BLACK NEWS CHANNEL','BLOOMBERG TV','Bloomberg Television','BOOMERANG','BOUNCE TV','BOUNCE TV Low','BUZZR','CBN NEWS INTERNATIONAL','C-SPAN','C-SPAN 2','C-SPAN 3','CARS TV'"

..use `-dc`

**Comment by halfagascan** [comment]
shees, you think I should read the directions?
thanks, I think this clears up my confusion
raven

**Comment by halfagascan** [comment]
I will close as solved.
Thanks for the help
raven
