### ISSUE TITLE
--tvh_start --tvh_offset is not considering group order anymore.

### ISSUE THREAD

**Issue by jobrien2001** [bebo-dot-dev/m3u-epg-editor#68]
Hello,

I recently updated the script, It used to consider the order in the group argument.

`-g="'sports','espn','dazn'" -t="100"`

Used to produce:
sports 1
espn 100
dazn 200

Produces now (alpha sorted)
dazn 1
espn 100
sports 200

How do i get the older functionality?

Thank you

**Comment by bebo-dot-dev** [comment]
try adding -no_sort (if you're using the CLI)

**Comment by jobrien2001** [comment]
-ns did not help.

**Comment by bebo-dot-dev** [comment]
I'll need your source m3u and your complete CLI args to be able to see what's happening. If you're able to supply that, strip out everything sensitive in your args and source data and I'll take a look asap.

**Comment by bebo-dot-dev** [comment]
Closed as abandoned
