### ISSUE TITLE
"groups" in config seem to be using wildcard

### ISSUE THREAD

**Issue by trix7777** [bebo-dot-dev/m3u-epg-editor#69]
Eg. using "groupmode": "keep":
   "groups": [
        "United States"
	],
will get the group "United States" but also a group named "24/7 United States".

Thanks for your work! Please check out my project m2strm.

**Comment by trix7777** [comment]
Sorry, confused as I was without drinking my morning coffee I forgot that I could use regex in the config even for groups, this was the solution (must start and end with):
"groups": [
"^United States$"
],

**Comment by bebo-dot-dev** [comment]
Thanks for adding your found fix, very helpful for future me and other people :)
