### ISSUE TITLE
Reference to #75

### ISSUE THREAD

**Issue by halfagascan** [bebo-dot-dev/m3u-epg-editor#80]
bebo-dot-dev
Not really an issue, but may help.
As you know from my past issues, a particular provider has poorly constructed links to icons.
In scouring for a fix, I came across rpl,  [https://tracker.debian.org/pkg/rpl](url) replace strings in files.
rpl is a UN*X text replacement utility. It will replace strings with new strings in multiple text files. It can work recursively over directories and supports limiting the search to specific file suffixes.
It is simple as: '</usr/bin/rpl -i -- 'https:/provider' 'https://provider' `playlist.m3u8`
The reference to bug 75 had requested linking a different icon source.
Hope thats helpful
Thanks

**Comment by bebo-dot-dev** [comment]
Thank you for the heads up on repl, it will help anyone who finds this issue. 

Another linux option for recursive replacement returnof values in files is sed (stream editor). Both repl and sed are mentioned in https://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files/112024#112024 with usage examples.
