### ISSUE TITLE
EPG output is blank?

### ISSUE THREAD

**Issue by ls-milkyway** [bebo-dot-dev/m3u-epg-editor#84]
**Describe the bug**
Trying to implement on the epg: [https://github.com/matthuisman/i.mjh.nz/raw/master/SamsungTVPlus/all.xml.gz](url)
m3u8 file generated is perfect...but epg xml file is blank??

**Required To Reproduce**
*When requesting support for something not working as expected all of the following are required. Issues not supplying all items will be closed. Please supply sanitised data files with username/passwords removed and attach the smallest files possible that reliably reproduce to the issue.*
1. **All** input arguments passed to the script CLI / **complete** input --json_cfg configuration.

2. Using only CLI command:

3. python3 ./m3u-epg-editor-py3.py -m="https://cutt.ly/ZeTNyZnn" -e="https://github.com/matthuisman/i.mjh.nz/raw/master/SamsungTVPlus/all.xml.gz" -g="'India','Canada','United States','United Kingdom'" -pc -ns -d="/home/rana/iptv" -f="m3u-new"

4. A sample input m3u data file and an epg data file (if in use).
 
M3U8 url is [[https://cutt.ly/ZeTNyZnn](url)
EPG url is [https://github.com/matthuisman/i.mjh.nz/raw/master/SamsungTVPlus/all.xml.gz](url)

5. The --log_enabled log file of a run where the problem occurred.
Forgot log option ...see if you can find the root cause without log.

**Additional context**
I guess your code is for some IPTV services as mentioned in rhe readme...specify if this can be implemented on the above mentioned repo.

**Comment by bebo-dot-dev** [comment]
Please supply the actual m3u file that was processed that you believe is paired against the EPG file that you've applied.

I'm not willing or able to try and guess at the data that you're using. 

If you can't this will be closed won't fix.

**Comment by bebo-dot-dev** [comment]
I ran a test with your input data

```
"m3uurl": "https://cutt.ly/ZeTNyZnn",
"epgurl": "https://github.com/matthuisman/i.mjh.nz/raw/master/SamsungTVPlus/all.xml.gz"
```

With `"log_enabled": true` this is the process log for the test run: [process.log](https://github.com/user-attachments/files/17083780/process.log)

These are the resulting generated files (file extensions changed to .txt to enable attach here):
* [84.m3u8](https://github.com/user-attachments/files/17083787/84.m3u8.txt)
* [84.xml](https://github.com/user-attachments/files/17083788/84.xml.txt)

This is the output of `no_epg_channels.txt` for the test run: [no_epg_channels.txt](https://github.com/user-attachments/files/17083782/no_epg_channels.txt)

From the readme
> no_epg_channels.txt
This is a log of any channels that you decided to keep that were subsequently found to have no epg data available. 

There is no EPG data in the xml file for the channels in the m3u file.

This can't and won't work, m3u data channels vs EPG data channels are unmatched, this is why the resulting generated EPG XML contains no channels.
