### ISSUE TITLE
Add example on sample config on request_headers

### ISSUE THREAD

**Issue by estrellagus** [bebo-dot-dev/m3u-epg-editor#85]
Having issues with a provider where the request errors out. However, If I do a request with headers simulating a Chrome browser, the files are downloaded fine.  

I have tried to add to the json config the headers below but have not been successful.  Was able to test these work as hardcoded on program logic. However, think would be helpful for others to see how to add to the config file. 

The headers I have used are -

    "request_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1" },

**Comment by bebo-dot-dev** [comment]
Hi @estrellagus 

There's an example in this issue comment:

https://github.com/bebo-dot-dev/m3u-epg-editor/issues/66#issuecomment-950154015

Your config looks close but I'm guessing it's not working because the values need to be supplied as an array. 

Give that a try with your header values and let me know if it works, if it does I'll update the sample.

**Comment by estrellagus** [comment]
Tried the details on the enclosed and it does work !  I thought I tried that but obviously not. 

Thank yo ufos a great program

**Comment by bebo-dot-dev** [comment]
You're welcome, great to hear that you got it working @estrellagus 

[The sample JSON configuration file](https://github.com/bebo-dot-dev/m3u-epg-editor/blob/main/sample_input_args.json) now includes `request_headers` values to improve the documentation around how this argument works.

Thank you for creating this issue.
